sensors:
  break_beam_1:
    type: break_beam
    pose:
      xyz: [1.6, 2.25, 0.91]
      rpy: [0, 0, 'pi']
  logical_camera_1:
    type: logical_camera
    pose:
      xyz: [-0.3, -1.916, 1.5]      
      rpy: [0, 'pi/2', 0]
  logical_camera_2:
    type: logical_camera
    pose:
      xyz: [-0.3, -1.15, 1.5]
      rpy: [0, 'pi/2', 0]
  logical_camera_3:
    type: logical_camera
    pose:
      xyz: [-0.3, -0.383, 1.5]
      rpy: [0, 'pi/2', 0]
  logical_camera_4:
    type: logical_camera
    pose:
      xyz: [-0.3, 0.383, 1.5]
      rpy: [0, 'pi/2', 0]
  logical_camera_5:
    type: logical_camera
    pose:
      xyz: [-0.3, 1.15, 1.5]
      rpy: [0, 'pi/2', 0]
  logical_camera_6:
    type: logical_camera
    pose:
      xyz: [-0.3, 1.916, 1.5]
      rpy: [0, 'pi/2', 0]
  logical_camera_7:
    type: logical_camera
    pose:
      xyz: [0.3, 3.15, 1.5]
      rpy: [0, 'pi/2', 0]
  logical_camera_9:
    type: logical_camera
    pose:
      xyz: [0.3, -3.15, 1.5]
      rpy: [0, 'pi/2', 0]
  logical_camera_10:
    type: logical_camera
    pose:
      xyz: [1.2, 2.25, 1.5]
      rpy: [0, 'pi/2', 0]

